# Generated by Django 4.2.7 on 2023-11-19 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_customer_model_product_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_model",
            name="is_sale",
            field=models.BooleanField(default=True, verbose_name="شامل تخفیف میشود"),
        ),
        migrations.AddField(
            model_name="product_model",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="قیمت تخفیف خورده",
            ),
        ),
        migrations.AlterField(
            model_name="customer_model",
            name="credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="اعتبار",
            ),
        ),
        migrations.AlterField(
            model_name="product_model",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="قیمت محصول",
            ),
        ),
        migrations.CreateModel(
            name="Order_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ سفارش"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, verbose_name="آدرس سفارش\u200c"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("u", "در دست آماده\u200cسازی"), ("r", "آماده تحویل")],
                        default="u",
                        max_length=1,
                        verbose_name="وضعیت سفارش",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="تعداد")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.customer_model",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product_model",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
    ]
